### PR TITLE
Purchase #14

### PR DESCRIPTION
**Pull request by jw2340**
User that has address in database can place order

Things I didn't get to:
- user can fill out address form and place order
- guest user can fill out address form and place order

### CODE REVIEW

**Comment by akhaya** [comment]
@jw2340 Addresses are associated with orders, not users, so shouldn't we be able to have the same flow for both? They enter the address and it gets saved to the order?
but create address first and in the .then create the order (to avoid address validation error)
As of right now - my orders aren't saving, and neither are the addresses.

**Comment by jw2340** [comment]
@akhaya 
i didn't get to saving addresses in the form. only users that already have addresses can process their order. that should work when you run the app.

yeah i think what you said makes sense for what would go on the route. but i was having trouble on the front end with passing the values from the form (which are saved on local state) and then dispatching them. check components/AddressForm - line 25. this.props is undefined in the handleSubmit function. i don't think it's something i'll be able to figure out tonight, but if you want to take a shot at, feel free to edit the code.

**Comment by akhaya** [comment]
@jw2340 AHA! I found the issue me thinks - you didnt bind the handleSubmit method on address form, once you do - "this" inside it works, so you can log out props and state.

**Comment by jw2340** [comment]
@akhaya ok thanks!

so now i'm almost done with guest user placing order. i got the address to save to the database. but i'm having trouble creating the order in the route, probably some small thing. if you want to check, the problem is at server/orders.js - line 244-250

ahhh, we're so close

**Comment by jw2340** [comment]
@akhaya i made some changes to my local branch but can't push anymore.
error: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes

**Pull request closed without merging**
