### PR TITLE
deleting and updating order status as admin, refactor admin tables

### PR DESCRIPTION
**Pull request by akhaya**
closes issues #27

### CODE REVIEW

**Comment by cleverettgirl** [comment]
@akhaya className = 'active' on the first `li` is why that border on user isn't changing when you go to different tabs (bootstrap thing methinks). I could probably change this easily, if you'd like me to do that.

**Comment by akhaya** [comment]
@cleverettgirl omg yes plz

**Comment by cleverettgirl** [comment]
@akhaya also, when you click deactivate, should it switch to activate so that you can re-activate a user after he/she has been deactivated?

**Comment by akhaya** [comment]
@cleverettgirl good question - so we don't have a re-activate method...lets discuss

**Pull request merged**
